<div id="footer-outer">
  <footer id="footer" class="wrapper">
    <div class="inner">
      <div id="footer-copyright">
        &copy; {{ moment(Date.now()).year() }} <a href="https://github.com/dumindu" target="_blank">{{ config.author }}</a><br>
        Powered by <a href="http://hexo.io/" target="_blank">Hexo</a> &amp; <a href="https://github.com/hexojs/site/tree/master/themes/navy" target="_blank">Navy</a> theme.
      </div>
    </div>
  </footer>
</div>