<div id="footer-outer">
  <footer id="footer" class="wrapper">
    <div class="inner">
      <div id="footer-copyright">
        &copy; {{ moment(Date.now()).year() }} <a href="https://github.com/dumindu" target="_blank">{{ config.author }}</a><br>
        Powered by <a href="http://hexo.io/" target="_blank">Hexo</a> &amp; <a href="https://github.com/hexojs/site/tree/master/themes/navy" target="_blank">Navy</a> theme.
      </div>
      <div id="footer-links">
        <a class="footer-link" href="https://www.buymeacoffee.com/dumindu" target="_blank">
          <img src="https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png" alt="Buy Me A Coffee" style="height: auto !important;width: auto !important;" >
        </a>
      </div>
    </div>
  </footer>
</div>