name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Checkout
        uses: actions/checkout@v6
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
